backend:
  name: git-gateway
  branch: main  # Replace with your GitHub branch if not 'main'
media_folder: public/img  # Folder for uploaded images
public_folder: /img
collections:
  - name: blog
    label: Blog
    folder: content/posts  # Where posts will be stored
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Author, name: author, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Body, name: body, widget: markdown }